matrix:
    include:
        # works on Precise and Trusty
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
          env:
              - CC=gcc-7
              - CXX=g++-7

language: cpp

before_install:
    - lsb_release -a
    - which clang
    - which clang++

install:
    - sudo apt-get -y install wget
    - sudo apt-get -y install iproute2
    - wget -nd https://github.com/google/googletest/archive/release-1.10.0.tar.gz
    - tar zxvf release-1.10.0.tar.gz

before_script:
    - pwd
    - ls -l
    - ip a
    - ./configure --with-gtest-source=`pwd`/googletest-release-1.10.0

script:
    - make
    - make check

notifications:
    recipients:
        - spam.travis@klub.com.pl
    email:
        on_success: change
        on_failure: always
